# Generates every icon surface in the repo from the tiered source art in
# resources/images/. Run from the repository root (Windows dev machine):
#
#   pnpm icons:generate
#
# The source files are 1024x1024 PNGs with transparency; the file names describe
# the *render size each variant was drawn for* (ico-xsmall for 32px render,
# ico-small for 64, ico-medium for 128, ico-large for 256, ico-large-x for
# 512+ and masters). Each output size below is rendered from the closest tier
# so small icons keep the simplified artwork instead of a crushed 1024px image.
#
# Outputs:
#   web     packages/web/public/favicon.ico (16/32/48) and packages/web/public/icons/*
#           (manifest icons 72-512, favicon PNGs, apple-touch-icon, shortcut icons)
#   desktop packages/web/src-tauri/icons/* (regenerated by `tauri icon` from the master)
#   mobile  packages/mobile/assets/{icon,adaptive-icon,splash-icon}.png,
#           Android mipmap launchers (PNG replaces the template .webp files),
#           and the density-specific splashscreen_logo.png drawables.
#
# CI never runs this script; it runs `pnpm icons:check`
# (tools/generation/check-app-icons.mjs) against the committed artifacts.

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '../..')).Path
$sourceDir = Join-Path $repoRoot 'resources/images'

$tiers = @(
    [pscustomobject]@{ Name = 'ico-xsmall'; Target = 32 }
    [pscustomobject]@{ Name = 'ico-small'; Target = 64 }
    [pscustomobject]@{ Name = 'ico-medium'; Target = 128 }
    [pscustomobject]@{ Name = 'ico-large'; Target = 256 }
    [pscustomobject]@{ Name = 'ico-large-x'; Target = 512 }
)

# Load each tier once; ties resolve to the smaller tier.
$loaded = @{}
foreach ($tier in $tiers) {
    $path = Join-Path $sourceDir "$($tier.Name).png"
    if (-not (Test-Path $path)) {
        throw "missing source tier: $path"
    }
    $loaded[$tier.Name] = [System.Drawing.Image]::FromFile($path)
}

function Get-TierForSize([int]$size) {
    $best = $null
    $bestDistance = [int]::MaxValue
    foreach ($tier in $tiers) {
        $distance = [Math]::Abs($tier.Target - $size)
        if ($distance -lt $bestDistance) {
            $bestDistance = $distance
            $best = $tier
        }
    }
    return $best.Name
}

function Get-ResizedPngBytes([int]$size, [string]$flattenHex) {
    $source = $loaded[(Get-TierForSize $size)]
    $bitmap = New-Object System.Drawing.Bitmap $size, $size
    $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
    try {
        $graphics.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
        $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
        $graphics.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality

        if ($flattenHex) {
            # Apple touch icons must be opaque: iOS composites transparency onto black.
            $brush = New-Object System.Drawing.SolidBrush ([System.Drawing.ColorTranslator]::FromHtml($flattenHex))
            $graphics.FillRectangle($brush, 0, 0, $size, $size)
            $brush.Dispose()
        }

        $attributes = New-Object System.Drawing.Imaging.ImageAttributes
        $attributes.SetWrapMode([System.Drawing.Drawing2D.WrapMode]::TileFlipXY)
        $destRect = New-Object System.Drawing.Rectangle 0, 0, $size, $size
        $graphics.DrawImage($source, $destRect, 0, 0, $source.Width, $source.Height, [System.Drawing.GraphicsUnit]::Pixel, $attributes)
        $attributes.Dispose()

        $stream = New-Object System.IO.MemoryStream
        $bitmap.Save($stream, [System.Drawing.Imaging.ImageFormat]::Png)
        # The comma wrapper keeps PowerShell from enumerating the byte[] into the
        # pipeline, which would collapse it to a single element at the call site.
        return , [byte[]]$stream.ToArray()
    }
    finally {
        $graphics.Dispose()
        $bitmap.Dispose()
    }
}

function Save-Png([string]$relativePath, [int]$size, [string]$flattenHex) {
    $absolutePath = Join-Path $repoRoot $relativePath
    $directory = Split-Path -Parent $absolutePath
    if (-not (Test-Path $directory)) {
        New-Item -ItemType Directory -Path $directory | Out-Null
    }
    [System.IO.File]::WriteAllBytes($absolutePath, (Get-ResizedPngBytes $size $flattenHex))
    Write-Host "  wrote $relativePath ($($size)x$($size))"
}


function Save-Ico([string]$relativePath, [int[]]$sizes) {
    # ICO container with PNG-compressed entries (supported by every modern browser).
    $entries = @()
    foreach ($size in $sizes) {
        $bytes = [byte[]](Get-ResizedPngBytes $size $null)
        if ($bytes.Count -lt 64) {
            throw "favicon.ico entry for ${size}px produced $($bytes.Count) bytes of PNG data"
        }
        $entries += [pscustomobject]@{ Size = $size; Bytes = $bytes }
    }

    $stream = New-Object System.IO.MemoryStream
    $writer = New-Object System.IO.BinaryWriter($stream)
    try {
        $writer.Write([uint16]0) # reserved
        $writer.Write([uint16]1) # type: icon
        $writer.Write([uint16]$entries.Count)

        $offset = 6 + (16 * $entries.Count)
        foreach ($entry in $entries) {
            $dimension = if ($entry.Size -ge 256) { 0 } else { $entry.Size }
            $writer.Write([byte]$dimension)
            $writer.Write([byte]$dimension)
            $writer.Write([byte]0) # palette
            $writer.Write([byte]0) # reserved
            $writer.Write([uint16]1) # color planes
            $writer.Write([uint16]32) # bits per pixel
            $writer.Write([uint32]$entry.Bytes.Length)
            $writer.Write([uint32]$offset)
            $offset += $entry.Bytes.Length
        }
        foreach ($entry in $entries) {
            $writer.Write([byte[]]$entry.Bytes)
        }

        $absolutePath = Join-Path $repoRoot $relativePath
        [System.IO.File]::WriteAllBytes($absolutePath, $stream.ToArray())
        Write-Host "  wrote $relativePath (sizes: $($sizes -join '/'))"
    }
    finally {
        $writer.Dispose()
        $stream.Dispose()
    }
}

$darkBackground = '#0f0f0f' # matches the app splash/manifest background color

Write-Host 'web: favicons + PWA manifest icons'
Save-Ico 'packages/web/public/favicon.ico' @(16, 32, 48)
Save-Png 'packages/web/public/icons/favicon-16x16.png' 16 $null
Save-Png 'packages/web/public/icons/favicon-32x32.png' 32 $null
Save-Png 'packages/web/public/icons/apple-touch-icon.png' 180 $darkBackground
foreach ($size in @(72, 96, 128, 144, 152, 192, 384, 512)) {
    Save-Png "packages/web/public/icons/icon-${size}x${size}.png" $size $null
}
Save-Png 'packages/web/public/icons/generate-icon.png' 96 $null
Save-Png 'packages/web/public/icons/drafts-icon.png' 96 $null

Write-Host 'mobile: expo assets (source of truth for future prebuilds/EAS builds)'
$masterPath = Join-Path $sourceDir 'ico-large-x.png'
foreach ($name in @('icon.png', 'adaptive-icon.png', 'splash-icon.png')) {
    $target = Join-Path $repoRoot "packages/mobile/assets/$name"
    $directory = Split-Path -Parent $target
    if (-not (Test-Path $directory)) {
        New-Item -ItemType Directory -Path $directory | Out-Null
    }
    Copy-Item $masterPath $target -Force
    Write-Host "  wrote packages/mobile/assets/$name (1024x1024 master)"
}

Write-Host 'mobile: android launcher icons (PNG replaces the template webp launchers)'
$launchers = @{
    'mdpi' = 48
    'hdpi' = 72
    'xhdpi' = 96
    'xxhdpi' = 144
    'xxxhdpi' = 192
}
foreach ($density in $launchers.Keys) {
    $size = $launchers[$density]
    Save-Png "packages/mobile/android/app/src/main/res/mipmap-$density/ic_launcher.png" $size $null
    Save-Png "packages/mobile/android/app/src/main/res/mipmap-$density/ic_launcher_round.png" $size $null
    # AAPT resolves @mipmap/ic_launcher by resource name, so the old .webp
    # files must go or both formats would collide.
    Get-ChildItem "packages/mobile/android/app/src/main/res/mipmap-$density" -Filter '*.webp' -ErrorAction SilentlyContinue |
        Remove-Item -Force
}

Write-Host 'mobile: android splash logo drawables'
$splashSizes = @{
    'mdpi' = 288
    'hdpi' = 432
    'xhdpi' = 576
    'xxhdpi' = 864
    'xxxhdpi' = 1152
}
foreach ($density in $splashSizes.Keys) {
    Save-Png "packages/mobile/android/app/src/main/res/drawable-$density/splashscreen_logo.png" $splashSizes[$density] $null
}

Write-Host 'desktop: regenerating the Tauri icon set from the 1024 master'
Push-Location (Join-Path $repoRoot 'packages/web')
try {
    pnpm exec tauri icon $masterPath
    if ($LASTEXITCODE -ne 0) {
        throw "tauri icon failed with exit code $LASTEXITCODE"
    }
}
finally {
    Pop-Location
}

# `tauri icon` also emits mobile scaffolding into src-tauri/gen (git-ignored).
# This repo ships mobile via Expo, so drop it to keep the tree clean. The old
# template placeholder icon source is equally dead now that icons come from
# resources/images/.
$generatedMobileDir = Join-Path $repoRoot 'packages/web/src-tauri/gen'
if (Test-Path $generatedMobileDir) {
    Remove-Item $generatedMobileDir -Recurse -Force
    Write-Host '  removed src-tauri/gen (Expo owns mobile, not Tauri)'
}
$placeholderIcon = Join-Path $repoRoot 'packages/web/src-tauri/icons/app-icon.svg'
if (Test-Path $placeholderIcon) {
    Remove-Item $placeholderIcon -Force
    Write-Host '  removed icons/app-icon.svg (template placeholder, unreferenced)'
}

foreach ($image in $loaded.Values) {
    $image.Dispose()
}

Write-Host 'done: all icon surfaces regenerated (commit the results)'
